################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# [nl]
# languageName = "Nl"
# languageCode = "nl-nl"
# contentDir = "content/dutch"
# weight = 1
